### ISSUE TITLE
Login Server params have changed

### ISSUE THREAD

**Issue by bonbombs** [ilikebits/pokemon-showdown-api#1]
I understand if you are no longer working on this. I happened to stumble into it today and had some trouble logging into the server. The Showdown server was returning an empty body as the response to the POST request needed to login.

Turns out the POST request parameters for logging in have changed from `password` to `pass`.

**Comment by elldritch** [comment]
Thanks for the find! I'm currently in a situation where it's difficult for me to write open source code, but I'd be more than happy to look at or push any PRs you have.

**Comment by elldritch** [comment]
Fixed by #2. Thanks all!
